  - platform: template
    sensors:
      day_of_week:
        unique_id: FO202408150345001
        friendly_name: "Day of Week"
        value_template: "{{ ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][now().weekday()] }}"
